FROM node:6
MAINTAINER Lu Pa <admin@tedic.org>

ENV DEBIAN_FRONTEND noninteractive
ENV CODE /usr/src/app

WORKDIR $CODE
COPY package.json .

# Copy code to conatiner volume
COPY . .
COPY docker-entrypoint.sh /

CMD ["npm","run","vigile"]

ENTRYPOINT ["/docker-entrypoint.sh"]
