module.exports = 
  twitter: require './chopsticks-module-twitter'
  fetcher: require './chopsticks-module-fetcher'
  mongodb: require './chopsticks-module-mongodb'
  jsonLoad: require './chopsticks-module-jsonLoad'
  companies: require './chopsticks-module-companies'
  analysis: require './chopsticks-module-analysis'
  ranks: require './chopsticks-module-ranks'
  fromList: require './chopsticks-module-fromList'
  stripper: require './chopsticks-module-stripper'
  resume: require './chopsticks-module-resume'
  leaders: require './chopsticks-module-leaders'
  reducer: require './chopsticks-module-reducer'
