# the order has sense now, just in case I forget..
module.exports = 
  source: require './chopsticks-module-source'
  ini: require './chopsticks-module-ini'
  diskCheck: require './chopsticks-module-diskCheck'
  stripper: require './chopsticks-module-stripper'
  resume: require './chopsticks-module-resume'
  fetcher: require './chopsticks-module-fetcher'
  jsonLoad: require './chopsticks-module-jsonLoad'
  companies: require './chopsticks-module-companies'
  analysis: require './chopsticks-module-analysis'
  ranks: require './chopsticks-module-ranks'
  leaders: require './chopsticks-module-leaders'
  reducer: require './chopsticks-module-reducer'
  mongodb: require './chopsticks-module-mongodb'
  twitter: require './chopsticks-module-twitter'
