#! /bin/sh

ISL="invi.sible.link"
if [ ! -d $ISL ]; 
    then echo `date +%H:%M` "invi.sible.link don't exists: failure in vigile scheduled running" >> /tmp/ISL.log ; 
    else
        cd $ISL
        # TODO, soon or later, this script shall execute different directions based on timezones and target of interest,
        # for example: mainstream media has to be checked around noon / 16 / 20 / 22 per national timezone
        date +%j-%Y >> /tmp/ISL.log
        node bin/directionTool.js
fi
